In [27]:
import numpy as np

The Basics

In [28]:
# 1-D array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [29]:
# 2-D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [30]:
#get dimension
a.ndim

1

In [31]:
# shape
b.shape
# (2,3)-> 2 row 3 columns
# a.shape(3,)-> 3 element 1 d array

(2, 3)

In [32]:
# datatype memory 
# int 32 by default
a.dtype

dtype('int32')

In [33]:
c=np.array([1,2,3],dtype="int16")
c.dtype

dtype('int16')

In [34]:
a.itemsize
# bcs 32 byte
# c.itemsize ->2

4

In [35]:
# total size
a.size * a.itemsize #no of element * size of element

12

In [36]:
# or totalsize
a.nbytes

12

Accessing Changing Specific Row Element Columns etc.

In [37]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
# Get specific element [row,column]
a[1,5]


13

In [39]:
a[1,-2] #negative index

13

In [40]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# specific coloumn
a[:,2]

array([ 3, 10])

In [42]:
# [startindex,endindex,stepindex]
a[0,1:6:2]

array([2, 4, 6])

In [43]:
# change data
a[1,5]=20

In [44]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [45]:
# all columns of same
a[:,2]=7
print(a)

[[ 1  2  7  4  5  6  7]
 [ 8  9  7 11 12 20 14]]


In [46]:
a[:,2]=[4,5]
print(a)

[[ 1  2  4  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3 D array

In [47]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [48]:
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [49]:
# 3d example

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
# get specific
c[0,1,1]

4

In [51]:
c.ndim

3