In [1]:
import numpy as np

The Basics

In [2]:
# 1-D array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2-D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#get dimension
a.ndim

1

In [ ]:
# shape
b.shape
# (2,3)-> 2 row 3 columns
# a.shape(3,)-> 3 element 1 d array

(2, 3)

In [7]:
# datatu=ype memory 
# int 32 by default
a.dtype

dtype('int32')

In [8]:
c=np.array([1,2,3],dtype="int16")
c.dtype

dtype('int16')

In [12]:
a.itemsize
# bcs 32 byte
# c.itemsize ->2

4

In [15]:
# total size
a.size * a.itemsize #no of element * size of element

12

In [ ]:
# or totalsize
a.nbytes

12

Accessing Changing Specific Row Element Columns etc.

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# Get specific element [row,column]
a[1,5]


13

In [ ]:
a[1,-2] #negative index

13

In [21]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# specific coloumn
a[:,2]

array([ 3, 10])

In [23]:
# [startindex,endindex,stepindex]
a[0,1:6:2]

array([2, 4, 6])

In [24]:
# change data
a[1,5]=20

In [25]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
# all columns of same
a[:,2]=7
print(a)

[[ 1  2  7  4  5  6  7]
 [ 8  9  7 11 12 20 14]]


In [27]:
a[:,2]=[4,5]
print(a)

[[ 1  2  4  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3 D array

In [28]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [29]:
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [31]:
# 3d example

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# get specific
c[0,1,1]

4

In [35]:
c.ndim

3