Initialzing Different Types Of Arrays

In [50]:
import numpy as np

In [51]:
# all zero
a=np.zeros(5)
print (a)


[0. 0. 0. 0. 0.]


In [52]:
a.ndim

1

In [53]:
b=np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [54]:
b.ndim

2

In [55]:
c=np.zeros((2,3,3))
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [56]:
c.ndim

3

In [57]:
d=np.zeros((2,3,3,2))
print(d)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [58]:
d.ndim

4

In [59]:
# All 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [60]:
# with dtype
np.ones((2,2),dtype="int32")

array([[1, 1],
       [1, 1]])

In [61]:
# Any onther number take (shape,number)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [62]:
e=np.zeros((2,3))
print (e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [63]:
np.full_like(e,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [64]:
np.full(e.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

Random value

In [ ]:
# random decimal value numbers 
# domt pass tuple
np.random.rand(4,2) #4x2 matrix

array([[0.46676164, 0.33965522],
       [0.19142765, 0.69669401],
       [0.73560648, 0.77161976],
       [0.73607249, 0.26892853]])

In [69]:
np.random.rand(4,2,3)


array([[[0.70721   , 0.06967328, 0.94851915],
        [0.19563899, 0.97243479, 0.82457135]],

       [[0.87377406, 0.14094512, 0.69076617],
        [0.15813078, 0.82767378, 0.67726871]],

       [[0.119627  , 0.45692152, 0.23036163],
        [0.37311625, 0.5106866 , 0.23884232]],

       [[0.57891775, 0.50677145, 0.26007572],
        [0.65090359, 0.94793869, 0.92055278]]])

In [71]:
np.random.random_sample(e.shape)

array([[0.49905055, 0.67720713, 0.47995782],
       [0.3388241 , 0.43504851, 0.61402637]])