Initialzing Different Types Of Arrays

In [425]:
import numpy as np

In [426]:
# all zero
a=np.zeros(5)
print (a)


[0. 0. 0. 0. 0.]


In [427]:
a.ndim

1

In [428]:
b=np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [429]:
b.ndim

2

In [430]:
c=np.zeros((2,3,3))
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [431]:
c.ndim

3

In [432]:
d=np.zeros((2,3,3,2))
print(d)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [433]:
d.ndim

4

In [434]:
# All 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [435]:
# with dtype
np.ones((2,2),dtype="int32")

array([[1, 1],
       [1, 1]])

In [436]:
# Any onther number take (shape,number)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [437]:
e=np.zeros((2,3))
print (e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [438]:
np.full_like(e,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [439]:
np.full(e.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

Random value

In [440]:
# random decimal value numbers 
# domt pass tuple
np.random.rand(4,2) #4x2 matrix

array([[0.19632167, 0.98506057],
       [0.24336569, 0.11749983],
       [0.29872831, 0.2699007 ],
       [0.38780072, 0.41260727]])

In [441]:
np.random.rand(4,2,3)


array([[[0.83429703, 0.8279809 , 0.35427943],
        [0.62786016, 0.89195302, 0.84030779]],

       [[0.74867059, 0.39643215, 0.65026559],
        [0.30980066, 0.16510335, 0.68515147]],

       [[0.49197265, 0.55409049, 0.84743475],
        [0.91045603, 0.06704864, 0.19929273]],

       [[0.00778238, 0.74907497, 0.49222917],
        [0.31967048, 0.28467462, 0.28867354]]])

In [442]:
np.random.random_sample(e.shape)

array([[0.33062537, 0.85057799, 0.07345986],
       [0.70607522, 0.38231438, 0.87543741]])

In [443]:
# Random integer value
np.random.randint(7) #take 0 as start by default and 7 exluded

0

In [444]:
np.random.randint(7,size=(3,3))

array([[4, 6, 3],
       [5, 3, 4],
       [6, 0, 1]])

In [445]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [446]:
# repeat
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0) #repeat 3 times and vertically
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1

In [447]:
np.array([[[[[1,1,1,1,1],
             [1,0,0,0,1],
             [1,0,9,0,1],
             [1,0,0,0,1],
             [1,1,1,1,1]]]]])

array([[[[[1, 1, 1, 1, 1],
          [1, 0, 0, 0, 1],
          [1, 0, 9, 0, 1],
          [1, 0, 0, 0, 1],
          [1, 1, 1, 1, 1]]]]])

In [448]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [449]:
output[1:4,1:4]=np.full(output[1:4,1:4].shape,0)

In [450]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [451]:
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [452]:
# sir solution

output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)


output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


<h3>
be <b>carefull</b> when copying array


In [453]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


its not copying in b its pointing variable to a location and haning in b reflect in a

In [454]:
# solution

c=np.array([1,2,3])
d=c.copy()
d[0]=100
print(c)
print(d)

[1 2 3]
[100   2   3]
