In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a*2

array([2, 4, 6, 8])

In [5]:
a/2


array([0.5, 1. , 1.5, 2. ])

In [6]:
b=np.array([2,2,2,2])
b+a

array([3, 4, 5, 6])

In [7]:
a**2


array([ 1,  4,  9, 16])

In [8]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

<h3> linear algebra

In [9]:
# mat multiplication

a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [11]:
# det
c=np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [12]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.min(stats)

1

In [14]:
np.max(stats)

6

In [15]:
np.max(stats,axis=0)

array([4, 5, 6])

In [16]:
np.max(stats,axis=1)

array([3, 6])

In [17]:
np.sum(stats)

21

<h3>Reorganizing Arrays

In [18]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print (before)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
after=before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [20]:
after=before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


vertically stacking


In [24]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

horizontal stack

In [25]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
h1=np.ones((2,4))
h2=np.zeros((2,2))

print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])