In [2]:
import numpy as np

load data from file

In [7]:
finaldata=np.genfromtxt('data.txt',delimiter=",")
finaldata

array([[1., 2., 3., 5., 6., 9., 5., 6., 5., 8., 9., 4., 6., 2., 4.],
       [5., 8., 5., 6., 5., 6., 4., 6., 4., 6., 6., 4., 7., 8., 1.],
       [4., 5., 6., 2., 9., 5., 6., 2., 6., 5., 2., 3., 2., 5., 2.]])

In [8]:
finaldata.astype('int32')

array([[1, 2, 3, 5, 6, 9, 5, 6, 5, 8, 9, 4, 6, 2, 4],
       [5, 8, 5, 6, 5, 6, 4, 6, 4, 6, 6, 4, 7, 8, 1],
       [4, 5, 6, 2, 9, 5, 6, 2, 6, 5, 2, 3, 2, 5, 2]])

advanced indexing and boolean masking

In [10]:
finaldata>5

array([[False, False, False, False,  True,  True, False,  True, False,
         True,  True, False,  True, False, False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True,  True, False,  True,  True, False],
       [False, False,  True, False,  True, False,  True, False,  True,
        False, False, False, False, False, False]])

In [12]:
finaldata[finaldata>5]

array([6., 9., 6., 8., 9., 6., 8., 6., 6., 6., 6., 6., 7., 8., 6., 9., 6.,
       6.])

In [14]:
# index with a list
a=np.array([1,2,34,5,67,8,9,5,6])
a[[1,2,-1]]

array([ 2, 34,  6])

In [ ]:
np.any(finaldata>5,axis=0) #check each column if any value in column greater than 5

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False])

In [ ]:
np.all(finaldata>5,axis=0) #all valus of column is >5

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [17]:
((finaldata>5) & (finaldata<8)) 

array([[False, False, False, False,  True, False, False,  True, False,
        False, False, False,  True, False, False],
       [False, False, False,  True, False,  True, False,  True, False,
         True,  True, False,  True, False, False],
       [False, False,  True, False, False, False,  True, False,  True,
        False, False, False, False, False, False]])

In [18]:
~((finaldata>5) & (finaldata<8)) 

array([[ True,  True,  True,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True],
       [ True,  True,  True, False,  True, False,  True, False,  True,
        False, False,  True, False,  True,  True],
       [ True,  True, False,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True]])