In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
b=np.array([255,255,30],dtype='uint8')

In [8]:
b.dtype

dtype('uint8')

In [9]:
b.itemsize

1

In [10]:
b[0]

255

In [11]:
b.size*b.itemsize

3

In [12]:
b.nbytes

3

In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
a.shape

(2, 3)

In [15]:
a.size

6

In [16]:
a[0]

array([1, 2, 3])

In [17]:
a[0,1]

2

In [18]:
a[0][0]

1

In [19]:
a[0][1]

2

In [20]:
a[0][1]

2

In [21]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [22]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
a[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a[0:]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
a.ndim

3

In [26]:
a[0][0]

array([1, 2, 3])

In [27]:
a[0][1]

array([4, 5, 6])

In [28]:
a[0][0][0]

1

In [29]:
a[0,0,0]

1

In [30]:
a[:2]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [31]:
a=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

In [32]:
a[0]

array([1, 2, 3, 4, 5, 6])

In [33]:
a[:0]

array([], shape=(0, 6), dtype=int32)

In [34]:
a[:1]

array([[1, 2, 3, 4, 5, 6]])

In [35]:
a[1]

array([4, 5, 6, 7, 8, 9])

In [36]:
a[1][1:]

array([5, 6, 7, 8, 9])

In [37]:
a[0,::-1]

array([6, 5, 4, 3, 2, 1])

In [38]:
a[::-1]

array([[4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6]])

In [39]:
a[::-1,::-1]

array([[9, 8, 7, 6, 5, 4],
       [6, 5, 4, 3, 2, 1]])

In [40]:
a

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [41]:
a[0,1]=30

In [42]:
a


array([[ 1, 30,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9]])

In [43]:
a[0,1:3]=40

In [44]:
a

array([[ 1, 40, 40,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9]])

In [45]:
a[:,::2]=70

In [46]:
a


array([[70, 40, 70,  4, 70,  6],
       [70,  5, 70,  7, 70,  9]])

In [47]:
a[0]=[1,2,3,4,5,6]

In [48]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [70,  5, 70,  7, 70,  9]])

In [49]:
a[:,2:6]=7

In [50]:
a

array([[ 1,  2,  7,  7,  7,  7],
       [70,  5,  7,  7,  7,  7]])

In [51]:
a[:,::2]=9

In [52]:
a

array([[9, 2, 9, 7, 9, 7],
       [9, 5, 9, 7, 9, 7]])

3d

In [53]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [54]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [56]:
c[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
print(c[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print(c[0,1])

[4 5 6]


In [59]:
d=np.array([[[1,2]]])

In [60]:
d

array([[[1, 2]]])

In [61]:
print(d)

[[[1 2]]]


In [62]:
d.size

2

In [63]:
d.ndim

3

In [64]:
e=np.array([[[[[[[[[[1,2]]]]]]]]]])

In [65]:
e.ndim

10

In [66]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [67]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [68]:
b[0,0]

array([1, 2, 3])

In [69]:
b[0,0,0]

1

In [71]:
a[0]

1

In [72]:
b[0][0]

array([1, 2, 3])

In [73]:
b[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
b[0].ndim

2

In [75]:
b[0][0].ndim

1

In [76]:
b[0][1]

array([4, 5, 6])

In [77]:
b[0][0][1]

2

In [78]:
c=np.array([[1,2,3],[4,5,6]])

In [79]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
c[0]

array([1, 2, 3])

In [81]:
c[0,1]

2

In [82]:
c[0,1:]

array([2, 3])

In [83]:
c[:,1:]

array([[2, 3],
       [5, 6]])

In [84]:
c[:,1]

array([2, 5])

In [85]:
d=list(c[:,1])

In [86]:
d

[2, 5]

In [87]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [90]:
b[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
b[0][:,1]

array([2, 5, 8])

In [92]:
b[0][::2,]

array([[1, 2, 3],
       [7, 8, 9]])

In [93]:
b[0][::2,::2]

array([[1, 3],
       [7, 9]])

In [95]:
a.size

3

In [97]:
b.size

9

In [98]:
a[0].size

1

In [99]:
a.itemsize

4

In [100]:
a.dtype

dtype('int32')

In [144]:
d=np.array([1,2,3],dtype="int16")

In [145]:
d

array([1, 2, 3], dtype=int16)

In [146]:
print(d.itemsize)
print(d)

2
[1 2 3]


In [147]:
d.dtype="int8"
print(d)

[1 0 2 0 3 0]


In [148]:
d.itemsize

1

In [149]:
d.nbytes

6

In [150]:
s=d.size*d.itemsize

In [151]:
s

6

In [152]:
d

array([1, 0, 2, 0, 3, 0], dtype=int8)

In [153]:
d[0]

1

In [154]:
print(d)

[1 0 2 0 3 0]


In [155]:
type(d)

numpy.ndarray

In [156]:
d.shape

(6,)

In [157]:
d[0:2]=3

In [158]:
d

array([3, 3, 2, 0, 3, 0], dtype=int8)

In [162]:
d[0:2]=[4,5]

In [163]:
d

array([4, 5, 2, 0, 3, 0], dtype=int8)