In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [66]:
b=np.array([255,255,30],dtype='uint8')

In [67]:
b.dtype

dtype('uint8')

In [68]:
b.itemsize

1

In [69]:
b[0]

255

In [71]:
b.size*b.itemsize

3

In [72]:
b.nbytes

3

In [73]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [74]:
a.shape

(2, 3)

In [75]:
a.size

6

In [76]:
a[0]

array([1, 2, 3])

In [77]:
a[0,1]

2

In [78]:
a[0][0]

1

In [79]:
a[0][1]

2

In [81]:
a[0][1]

2

In [83]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [84]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [85]:
a[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
a[0:]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [87]:
a.ndim

3

In [88]:
a[0][0]

array([1, 2, 3])

In [89]:
a[0][1]

array([4, 5, 6])

In [91]:
a[0][0][0]

1

In [92]:
a[0,0,0]

1

In [93]:
a[:2]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [101]:
a=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

In [102]:
a[0]

array([1, 2, 3, 4, 5, 6])

In [103]:
a[:0]

array([], shape=(0, 6), dtype=int32)

In [104]:
a[:1]

array([[1, 2, 3, 4, 5, 6]])

In [105]:
a[1]

array([4, 5, 6, 7, 8, 9])

In [106]:
a[1][1:]

array([5, 6, 7, 8, 9])

In [113]:
a[0,::-1]

array([6, 5, 4, 3, 2, 1])

In [114]:
a[::-1]

array([[4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6]])

In [115]:
a[::-1,::-1]

array([[9, 8, 7, 6, 5, 4],
       [6, 5, 4, 3, 2, 1]])

In [116]:
a

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [117]:
a[0,1]=30

In [118]:
a


array([[ 1, 30,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9]])

In [119]:
a[0,1:3]=40

In [120]:
a

array([[ 1, 40, 40,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9]])

In [121]:
a[:,::2]=70

In [122]:
a


array([[70, 40, 70,  4, 70,  6],
       [70,  5, 70,  7, 70,  9]])

In [123]:
a[0]=[1,2,3,4,5,6]

In [124]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [70,  5, 70,  7, 70,  9]])

In [125]:
a[:,2:6]=7

In [126]:
a

array([[ 1,  2,  7,  7,  7,  7],
       [70,  5,  7,  7,  7,  7]])

In [127]:
a[:,::2]=9

In [128]:
a

array([[9, 2, 9, 7, 9, 7],
       [9, 5, 9, 7, 9, 7]])

3d

In [129]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [130]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [131]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [132]:
c[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
print(c[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [138]:
print(c[0,1])

[4 5 6]


In [139]:
d=np.array([[[1,2]]])

In [140]:
d

array([[[1, 2]]])

In [141]:
print(d)

[[[1 2]]]


In [142]:
d.size

2

In [143]:
d.ndim

3

In [144]:
e=np.array([[[[[[[[[[1,2]]]]]]]]]])

In [145]:
e.ndim

10